// export const ON_PRINT_REQUEST = 'ON_PRINT_REQUEST';
export const ON_PRINT_FAILURE = 'ON_PRINT_FAILURE';
export const ON_PRINT_SUCCESS = 'ON_PRINT_SUCCESS';
export const ON_PRINT_TEMP_SUCCESS = 'ON_PRINT_TEMP_SUCCESS';
export const ON_PRINT_MAR_SUCCESS = 'ON_PRINT_MAR_SUCCESS';

// Chart Actions
export const SET_PATIENT_NAME = 'SET_PATIENT_NAME';
export const SET_RX_NUMBER = 'SET_RX_NUMBER';
export const SET_FORM_TYPE = 'SET_FORM_TYPE';
export const SET_DRUG = 'SET_DRUG';
export const SET_DOSE = 'SET_DOSE';
export const SET_TAKEHOME_DOSE = 'SET_TAKEHOME_DOSE';
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
export const SET_DAY_CARRY = 'SET_DAY_CARRY';
export const SET_CARRY_SCHEME = 'SET_CARRY_SCHEME';
export const SET_CARRY_SCHEME_OPTION = 'SET_CARRY_SCHEME_OPTION';

